name: test

on:
  push:
    paths:
      - .github/workflows/build_armbian.yaml

  
jobs:
    test-push:
        # container:
        #   image: ubuntu:22.04
        #   options: --privileged
        runs-on: ubuntu-latest
        strategy:
            matrix:
                image: [ 
                        # mirte_orangepizero2,
                        orangepi3b
                        ]
            fail-fast: false
        steps: 
          - name: Checkout
            uses: actions/checkout@v3
            with:
              repository: armbian/build
              ref: main
              path: build
          - run: |
              cd build
              ./compile.sh build BOARD=${{ matrix.image }} BRANCH=edge BUILD_DESKTOP=no BUILD_MINIMAL=no KERNEL_CONFIGURE=no RELEASE=noble
          - uses: actions/upload-artifact@v4
            with:
              name: build_${{ matrix.image }}
              path: build/output/images/*.img
          