name: Build and Upload

on:
    [push]
permissions:
    contents: write
  
jobs:
    shellcheck:
      uses: ./.github/workflows/shellcheck.yml
    shfmt:
      uses: ./.github/workflows/shfmt.yml
    build-and-push:
        # container:
        #   image: ubuntu:22.04
        #   options: --privileged
        runs-on: ubuntu-latest
        needs: [shellcheck, shfmt]
        strategy:
            matrix:
                image: [ 
                        # mirte_orangepizero2,
                        mirte_orangepi3b
                        ]
                type: [
                          default, mirte-master
                        ]
        
            fail-fast: false
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Extract branch name
              shell: bash
              run: |
                echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
                echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_OUTPUT
              id: extract_branch
            
            - name: setup this repo
              run: |
                    sudo apt update
                    sudo apt install qemu-user-static parted -y
                    ./packerInstall.sh
            - name: setup build files
              run: |
                  echo -e "MIRTE_TYPE=${{ matrix.type }}" >> settings.sh
                  cat settings.sh
                  # - name: setup repos
            #   run: |
            #     cp main_repos.yaml repos.yaml
            #     yq e -i '.repositories.mirte-ros-packages.version = "fix-intro-rob"' repos.yaml
            #     yq e -i '.repositories.mirte-telemetrix4arduino.url =  "https://github.com/arendjan/telemetrix4arduino.git"' repos.yaml
            #     yq e -i '.repositories.mirte-telemetrix4arduino.version = "fix-intro-robotics"' repos.yaml
            - name: Build
              run: |
                    ./packerBuild.sh ${{ matrix.image }}
            - name: artifacts
              uses: actions/upload-artifact@v4
              if: always()
              with:
                path: build/*.img.xz
                name: mirte_master_${{ matrix.image }}
            - name: Push to release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: build/*.img.xz
      
    upload_private_server:
      needs: [build-and-push]
      uses: ./.github/workflows/upload.yaml
      with:
        name: 'image'
      secrets: inherit
    build_installer_all:
      needs: [upload_private_server]
      uses: ./.github/workflows/build_installer.yaml
      secrets: inherit
            