name: build-virtualbox

on:
  push:

  
jobs:
    build-virtualbox:
        runs-on: ubuntu-latest
        steps: 
          - name: Checkout
            uses: actions/checkout@v4
          - run: |
              sudo apt update
              sudo apt install -y virtualbox
              ./packerInstall.sh
              mkdir git_local || true
              mkdir workdir || true
              mkdir logs || true
              mkdir build || true
              sudo packer build --only virtualbox-ovf.install_tests build.pkr.hcl
              ls -l build/
              ls -l workdir/

          - uses: actions/upload-artifact@v4
            with:
              name: build_${{ matrix.image }}
              path: build/output/images/*.img

 
    