name: Build and Upload

on:
    push:
    schedule:
      - cron: '0 4 * * 1' # every Monday at 4:00 AM  
permissions:
    contents: write
  
jobs:
    shellcheck:
      uses: ./.github/workflows/shellcheck.yml
    shfmt:
      uses: ./.github/workflows/shfmt.yml
    reposcheck:
      uses: ./.github/workflows/repocheck.yml
    build-and-push:
        needs: [shellcheck, shfmt, reposcheck]
        strategy:
            matrix:
                image: [ 
                        mirte_orangepizero2,
                        mirte_orangepi3b
                        ]
            fail-fast: false
        uses: ./.github/workflows/build_single.yaml
        with:
          sbc: ${{ matrix.image }}
        secrets: inherit
    master-build-and-push:
        needs: [shellcheck, shfmt, reposcheck]
        # strategy:
        #     matrix:
        #         image: [ 
        #                 # mirte_orangepizero2,
        #                 mirte_orangepi3b
        #                 ]
        #     fail-fast: false
        uses: ./.github/workflows/build_single.yaml
        with:
          mirte_type: mirte-master
          sbc: mirte_orangepi3b
        secrets: inherit
      
            
