name: Build and Upload

on:
    [push]
permissions:
    contents: write
  
jobs:
    shellcheck:
      uses: ./.github/workflows/shellcheck.yml
    shfmt:
      uses: ./.github/workflows/shfmt.yml
    build-and-push:
        # container:
        #   image: ubuntu:22.04
        #   options: --privileged
        runs-on: ubuntu-latest
        needs: [shellcheck, shfmt]
        uses: ./.github/workflows/build_single.yaml
        with: 
          download_artifacts: false
        strategy:
            matrix:
                image: [ 
                        # mirte_orangepizero2,
                        mirte_orangepi3b
                        ]
                type: [
                          default, mirte-master
                        ]
        
            fail-fast: false

      
    upload_private_server:
      needs: [build-and-push]
      uses: ./.github/workflows/upload.yaml
      with:
        name: 'image'
      secrets: inherit
    build_installer_all:
      needs: [upload_private_server]
      uses: ./.github/workflows/build_installer.yaml
      secrets: inherit
            