name: build-virtualbox

on:
  push:

  
jobs:
    build-virtualbox:
        runs-on: ubuntu-22.04
        steps: 
          - name: Checkout
            uses: actions/checkout@v4
          - run: |
              sudo apt update
              sudo apt install -y virtualbox linux-headers-generic linux-headers-$(uname -r)
              sudo apt install -y virtualbox-dkms
              sudo dpkg-reconfigure virtualbox-dkms
              sudo dpkg-reconfigure virtualbox
              sudo apt-get autoremove
              sudo /sbin/vboxconfig || true
              wget https://mirte.arend-jan.com/files/test/Armbian_Focal_Uefi.ova
              vboxmanage import Armbian_Focal_Uefi.ova
              vboxmanage startvm Armbian_Focal_Uefi --type headless


              ./packerInstall.sh
              mkdir git_local || true
              mkdir workdir || true
              mkdir logs || true
              mkdir build || true
              sudo packer build --only virtualbox-ovf.install_tests build.pkr.hcl
              ls -l build/
              ls -l workdir/

          - uses: actions/upload-artifact@v4
            with:
              name: build_${{ matrix.image }}
              path: build/output/images/*.img

 
    