name: Build and Upload

on:
    [push]
permissions:
    contents: write
  
jobs:
    shellcheck:
      uses: ./.github/workflows/shellcheck.yml
    shfmt:
      uses: ./.github/workflows/shfmt.yml
    build-and-push:
        # container:
        #   image: ubuntu:22.04
        #   options: --privileged
        # runs-on: ubuntu-latest
        needs: [shellcheck, shfmt]
        strategy:
            matrix:
                image: [ 
                        # mirte_orangepizero2,
                        mirte_orangepi3b
                        ]
                type: [
                          default, mirte-master
                        ]
        
            fail-fast: false
        uses: ./.github/workflows/build_single.yaml
        with:
          mirte_type: ${{ matrix.type }}
          sbc: ${{ matrix.image }}
        secrets: inherit
      
            