name: test

on:
  push:
    paths:
      - .github/workflows/build_armbian.yaml

  
jobs:
    build-armbian:
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                image: [
                        orangepi3b,
                        orangepizero2,
                        orangepizero
                        ]
                ubuntu: [
                        focal,
                        jammy,
                        noble
                        ]
                exclude:
                    - image: orangepi3b
                      ubuntu: focal
                    - image: orangepizero2
                      ubuntu: focal
            fail-fast: false
        steps: 
          - name: Checkout
            uses: actions/checkout@v4
            with:
              repository: arendjan/build
              ref: fix-orangepizero-wifi-usb-otg
              path: build
          - name: setup cache
            uses: actions/cache@v4
            with:
              path: build/cache
              key: ${{ runner.os }}-build-${{ matrix.image }}-${{ matrix.ubuntu }}
          - run: |
              cd build
              ./compile.sh build BOARD=${{ matrix.image }} BRANCH=edge BUILD_DESKTOP=no BUILD_MINIMAL=no KERNEL_CONFIGURE=no RELEASE=${{ matrix.ubuntu }}
          - uses: actions/upload-artifact@v4
            with:
              name: build_${{ matrix.image }}
              path: build/output/images/*.img

 
    