name: Upload to private server
on: 
  workflow_call:
    inputs:
      name:
        required: true
        type: string

permissions:
    contents: write
jobs:
    upload_private_server:
      if: false
      runs-on: ubuntu-22.04
      steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Extract branch name
              shell: bash
              run: |
                echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
                echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_OUTPUT
              id: extract_branch
            - name: Download artifact
              id: download
              uses: actions/download-artifact@v4
              with:
                path: upload

            - name: List artifact
              run: |
                ls ${{ github.workspace }}
                mkdir ${{ github.workspace }}/upload/mirte
                ls ${{ github.workspace }}/upload
                tree ${{ github.workspace }}/upload
                # for every file ending in .img.xz, remove last part of the path
                for file in $(find ${{ github.workspace }}/upload/ -name '*.img.xz'); do
                    f=$(basename $file)
                    echo $f
                    echo ${{ github.workspace }}/upload/mirte/"${f%_*_*_*_*}.${f#*.}"
                    mv $file ${{ github.workspace }}/upload/mirte/"${f%_*_*_*_*}.${f#*.}"
                done
            - name: Upload to private server
              if: ${{ !env.ACT }}
              run: |
                sudo apt update
                sudo apt install sshpass
                mkdir -p ~/.ssh
                ssh-keyscan arend-jan.com >> ~/.ssh/known_hosts
                export SSHPASS=${{ secrets.MIRTEFILES }}
                sshpass -e sftp mirtefiles@arend-jan.com << ASDF
                    rm files/${{ steps.extract_branch.outputs.branch }}_old_${{ inputs.name }}/*
                    rmdir files/${{ steps.extract_branch.outputs.branch }}_old_${{ inputs.name }}
                    rename files/${{ steps.extract_branch.outputs.branch }}_${{ inputs.name }} files/${{ steps.extract_branch.outputs.branch }}_old_${{ inputs.name }}
                    mkdir files/${{ steps.extract_branch.outputs.branch }}_${{ inputs.name }}
                    ! touch uploading.txt
                    put uploading.txt files/${{ steps.extract_branch.outputs.branch }}_${{ inputs.name }}/uploading.txt
                    put upload/mirte/* /files/${{ steps.extract_branch.outputs.branch }}_${{ inputs.name }}/
                    rm files/${{ steps.extract_branch.outputs.branch }}_${{ inputs.name }}/uploading.txt
                    bye
                ASDF
